baseURL = "https://blog.mtlevine0.com"
locale = "en-us"
title = "Matt Levine's Blog"
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false

[params]
  author = "Matt Levine"
  description = "Personal blog"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true

[params.homeInfoParams]
  Title = "Hi, I'm Matt"
  Content = "Welcome to my blog."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/mtlevine0"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[outputs]
  home = ["HTML", "RSS", "JSON"]

[services]
  [services.googleAnalytics]
    ID = "G-N1GFLRZM7D"
